name: Deploy
on:
  push:
    branches:
      - main

jobs:
  update-s3-assets:
    name: Update s3 assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: assets.tribonera.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'assets'